INSERT INTO courses (id, name, name_mm, description, price_amount, currency)
VALUES ('course-1', 'Basic Thai Grammar Course', 'ထိုင်းစာ အဓိက သဒ္ဒါသင်တန်း', 'Basic Thai Grammar Handbook', 35000, 'MMK')
ON CONFLICT(id) DO NOTHING;

DELETE FROM grammar_ext;

INSERT INTO grammar_ext (id, course_id, chapter_number, title, title_myanmar, explanation, explanation_myanmar, examples_json, order_index) VALUES
('g-001', 'course-basic', 1, 'Basic Word Order (SVO)', 'အခြေခံ ဝါကျတည်ဆောက်ပုံ', 'Thai follows Subject-Verb-Object (SVO) order just like English.', 'ထိုင်းစာသည် အင်္ဂလိပ်စာကဲ့သို့ပင် ကတ္တား-ကြိယာ-ကံ (Subject-Verb-Object) အစီအစဉ်အတိုင်း ရေးသားသည်။', '[{"thai": "ฉันกินข้าว", "phonetic": "chăn gin kâao", "english": "I eat rice.", "myanmar": "ကျွန်တော် ထမင်းစားတယ်။"}]', 1),
('g-002', 'course-basic', 1, 'Negation with ไม่ (mâi)', 'ไม่ (mâi) ဖြင့် အငြင်းဝါကျပြလုပ်ခြင်း', 'To make a sentence negative, place ไม่ (mâi) directly before the verb.', 'အငြင်းဝါကျပြုလုပ်ရန် မူလကြိယာ၏ရှေ့တည့်တည့်တွင် ไม่ (mâi) ကို ထည့်ရသည်။', '[{"thai": "เขาไม่ไป", "phonetic": "kăo mâi bpai", "english": "He does not go.", "myanmar": "သူ မသွားဘူး။"}]', 2),
('g-003', 'course-basic', 1, 'Yes/No Questions with ไหม (măi)', 'ไหม (măi) ဖြင့် မေးခွန်းမေးခြင်း', 'Add ไหม (măi) at the end of a sentence to turn it into a yes/no question.', 'ဝါကျအဆုံးတွင် ไหม (măi) ထည့်ခြင်းဖြင့် ဟုတ်/မဟုတ် (Yes/No) မေးခွန်းဖြစ်စေသည်။', '[{"thai": "คุณหิวไหม", "phonetic": "kun hĭw măi", "english": "Are you hungry?", "myanmar": "ခင်ဗျား ဗိုက်ဆာလား။"}]', 3),
('g-004', 'course-basic', 2, 'Past Tense Marker แล้ว (láew)', 'ပြီးခဲ့သောအချိန်ပြ แล้ว (láew)', 'แล้ว (láew) means "already" and is placed at the end of a sentence to indicate a past action.', 'แล้ว (láew) သည် "ပြီးပြီ" ဟု အဓိပ္ပါယ်ရပြီး ဝါကျအဆုံးတွင်ထား၍ အတိတ်ကာလကို ပြသည်။', '[{"thai": "ฉันกินแล้ว", "phonetic": "chăn gin láew", "english": "I already ate.", "myanmar": "ကျွန်တော် စားပြီးပြီ။"}]', 4),
('g-005', 'course-basic', 2, 'Future Tense Marker จะ (jà)', 'အနာဂတ်ကာလပြ จะ (jà)', 'จะ (jà) means "will" and is placed before the verb to indicate future tense.', 'จะ (jà) သည် "လိမ့်မည်" ဟု အဓိပ္ပါယ်ရပြီး ကြိယာရှေ့တွင်ထား၍ အနာဂတ်ကာလကို ပြသည်။', '[{"thai": "ฉันจะไปพรุ่งนี้", "phonetic": "chăn jà bpai prûng-née", "english": "I will go tomorrow.", "myanmar": "ကျွန်တော် မနက်ဖြန် သွားမယ်။"}]', 5),
('g-006', 'course-basic', 2, 'Present Continuous กำลัง (gam-lang)', 'လက်ရှိဖြစ်ဆဲကာလပြ กำลัง (gam-lang)', 'กำลัง (gam-lang) is placed before the verb to show an action is currently happening.', 'กำลัง (gam-lang) ကို ကြိယာရှေ့တွင်ထား၍ လက်ရှိလုပ်ဆောင်နေဆဲဖြစ်ကြောင်း ပြသည်။', '[{"thai": "เขากำลังกิน", "phonetic": "kăo gam-lang gin", "english": "He is eating.", "myanmar": "သူ စားနေတယ်။"}]', 6),
('g-007', 'course-basic', 3, 'Polite Particles ครับ/ค่ะ (kráp/kâ)', 'ယဉ်ကျေးသော စကားအဆုံးသတ်များ', 'ครับ (kráp) is used by male speakers, and ค่ะ (kâ) by female speakers at the end of sentences for politeness.', 'ครับ (kráp) ကို ယောကျ်ားလေးများ၊ ค่ะ (kâ) ကို မိန်းကလေးများက ယဉ်ကျေးမှုအရ ဝါကျအဆုံးတွင် သုံးသည်။', '[{"thai": "ขอบคุณครับ", "phonetic": "kòp kun kráp", "english": "Thank you (male speaker).", "myanmar": "ကျေးဇူးတင်ပါတယ် (ယောကျ်ားလေး)။"}]', 7),
('g-008', 'course-basic', 3, 'The Verb "To Be" (เป็น / คือ)', 'ဖြစ်သည် ကြိယာ (เป็น / คือ)', 'เป็น (bpen) is used for state/status, while คือ (keu) is used for definitions/equations.', 'เป็น ကို အခြေအနေနှင့် အဆင့်အတန်းပြရာတွင် သုံးပြီး၊ คือ ကို အဓိပ္ပါယ်ဖွင့်ဆိုရာတွင် သုံးသည်။', '[{"thai": "เขาเป็นหมอ", "phonetic": "kăo bpen mŏr", "english": "He is a doctor.", "myanmar": "သူက ဆရာဝန်ဖြစ်တယ်။"}]', 8),
('g-009', 'course-basic', 3, 'The Verb "To Have" (มี - mee)', 'ရှိသည် ကြိယာ มี (mee)', 'มี (mee) means "to have" or "there is/there are".', 'มี သည် "ရှိသည်" ဟု အဓိပ္ပါယ်ရသည်။', '[{"thai": "ฉันมีหมา", "phonetic": "chăn mee măa", "english": "I have a dog.", "myanmar": "ကျွန်တော့်မှာ ခွေးတစ်ကောင်ရှိတယ်။"}]', 9),
('g-010', 'course-basic', 4, 'Wanting something อยาก (yàak)', 'လိုချင်ခြင်းပြ อยาก (yàak)', 'อยาก (yàak) + verb means "want to do something". (เอา is used for objects).', 'อยาก ကို ကြိယာရှေ့မှာထားပါက "လုပ်ချင်တယ်" လို့ အဓိပ္ပါယ်ရပါတယ်။ (ပစ္စည်းလိုချင်လျှင် เอา ကိုသုံးပါ)', '[{"thai": "ฉันอยากไป", "phonetic": "chăn yàak bpai", "english": "I want to go.", "myanmar": "ကျွန်တော် သွားချင်တယ်။"}]', 10),
('g-011', 'course-basic', 4, 'Must / Have to ต้อง (dtông)', 'လုပ်ရမည်ပြ ต้อง (dtông)', 'ต้อง (dtông) is placed before the verb to indicate necessity or obligation.', 'ต้อง ကို ကြိယာရှေ့တွင်ထား၍ မဖြစ်မနေ လုပ်ရမည်ဟု ပြသည်။', '[{"thai": "ฉันต้องไป", "phonetic": "chăn dtông bpai", "english": "I must go.", "myanmar": "ကျွန်တော် သွားရမယ်။"}]', 11),
('g-012', 'course-basic', 4, 'Can / Ability ได้ (dâai)', 'နိုင်သည်ပြ ได้ (dâai)', 'ได้ (dâai) placed after the verb means "can" (possibility/permission).', 'ได้ ကို ကြိယာနောက်တွင်ထား၍ "နိုင်သည်" သို့မဟုတ် "ခွင့်ပြုသည်" ဟု အဓိပ္ပါယ်ရသည်။', '[{"thai": "ทำได้ไหม", "phonetic": "tam dâai măi", "english": "Can you do it?", "myanmar": "လုပ်လို့ရလား။"}]', 12),
('g-013', 'course-basic', 5, 'Adjective Placement', 'နာမဝိသေသန နေရာထားရှိပုံ', 'In Thai, adjectives always come AFTER the noun they describe.', 'ထိုင်းဘာသာတွင် နာမဝိသေသန (အထူးပြုစကားလုံး) သည် အမြဲတမ်း နာမ် (အရာဝတ္ထု) နောက်တွင် လိုက်သည်။', '[{"thai": "หมาใหญ่", "phonetic": "măa yài", "english": "Big dog", "myanmar": "ခွေးကြီး"}]', 13),
('g-014', 'course-basic', 5, 'Who ใคร (krai)', 'ဘယ်သူ ใคร (krai)', 'ใคร (krai) means "who".', 'ใคร သည် "ဘယ်သူ" ဟု အဓိပ္ပါယ်ရသည်။', '[{"thai": "เขาคือใคร", "phonetic": "kăo keu krai", "english": "Who is he?", "myanmar": "သူ ဘယ်သူလဲ။"}]', 14),
('g-015', 'course-basic', 5, 'What อะไร (à-rai)', 'ဘာလဲ อะไร (à-rai)', 'อะไร (à-rai) means "what".', 'อะไร သည် "ဘာလဲ" ဟု အဓိပ္ပါယ်ရသည်။', '[{"thai": "นี่คืออะไร", "phonetic": "nêe keu à-rai", "english": "What is this?", "myanmar": "ဒါ ဘာလဲ။"}]', 15),
('g-016', 'course-basic', 6, 'Where ที่ไหน (têe-năi)', 'ဘယ်မှာ ที่ไหน (têe-năi)', 'ที่ไหน (têe-năi) means "where".', 'ที่ไหน သည် "ဘယ်မှာ" ဟု အဓိပ္ပါယ်ရသည်။', '[{"thai": "ห้องน้ำอยู่ที่ไหน", "phonetic": "hông náam yòo têe-năi", "english": "Where is the toilet?", "myanmar": "အိမ်သာ ဘယ်မှာလဲ။"}]', 16),
('g-017', 'course-basic', 6, 'When เมื่อไหร่ (mêua-rài)', 'ဘယ်အချိန် เมื่อไหร่ (mêua-rài)', 'เมื่อไหร่ (mêua-rài) means "when".', 'เมื่อไหร่ သည် "ဘယ်အချိန်" ဟု အဓိပ္ပါယ်ရသည်။', '[{"thai": "คุณจะมาเมื่อไหร่", "phonetic": "kun jà maa mêua-rài", "english": "When will you come?", "myanmar": "ခင်ဗျား ဘယ်အချိန် လာမလဲ။"}]', 17),
('g-018', 'course-basic', 6, 'Classifiers ลักษณนาม', 'အရေအတွက်ပြစကားလုံး', 'Thai uses specific classifiers when counting (Noun + Number + Classifier).', 'ပစ္စည်းများကို ရေတွက်ရာတွင် သီးသန့်အရေအတွက်ပြစကားလုံး (ပစ္စည်း + ဂဏန်း + အမျိုးအစား) ပုံစံဖြင့် သုံးသည်။', '[{"thai": "หมา 2 ตัว", "phonetic": "măa sŏng dtua", "english": "2 dogs", "myanmar": "ခွေး ၂ ကောင်"}]', 18),
('g-019', 'course-basic', 7, 'Conjunction และ (láe)', 'နှင့် / ပြီးတော့ และ (láe)', 'และ (láe) means "and", used to connect nouns or clauses.', 'และ သည် "နှင့်" သို့မဟုတ် "ပြီးတော့" ဟု အဓိပ္ပါယ်ရပြီး စကားလုံး သို့မဟုတ် ဝါကျများကို ဆက်ပေးသည်။', '[{"thai": "ฉันและเขา", "phonetic": "chăn láe kăo", "english": "Me and him", "myanmar": "ကျွန်တော်နှင့် သူ"}]', 19),
('g-020', 'course-basic', 7, 'Conjunction แต่ (dtàe)', 'ဒါပေမဲ့ แต่ (dtàe)', 'แต่ (dtàe) means "but".', 'แต่ သည် "ဒါပေမဲ့" ဟု အဓိပ္ပါယ်ရသည်။', '[{"thai": "แพงแต่ดี", "phonetic": "paeng dtàe dee", "english": "Expensive but good", "myanmar": "ဈေးကြီးပေမဲ့ ကောင်းတယ်"}]', 20),

('g-101', 'course-1', 1, 'Basic Word Order (SVO)', 'အခြေခံ ဝါကျတည်ဆောက်ပုံ', 'Thai follows Subject-Verb-Object (SVO) order just like English.', 'ထိုင်းစာသည် အင်္ဂလိပ်စာကဲ့သို့ပင် ကတ္တား-ကြိယာ-ကံ (Subject-Verb-Object) အစီအစဉ်အတိုင်း ရေးသားသည်။', '[{"thai": "ฉันกินข้าว", "phonetic": "chăn gin kâao", "english": "I eat rice.", "myanmar": "ကျွန်တော် ထမင်းစားတယ်။"}]', 1),
('g-102', 'course-1', 1, 'Negation with ไม่ (mâi)', 'ไม่ (mâi) ဖြင့် အငြင်းဝါကျပြလုပ်ခြင်း', 'To make a sentence negative, place ไม่ (mâi) directly before the verb.', 'အငြင်းဝါကျပြုလုပ်ရန် မူလကြိယာ၏ရှေ့တည့်တည့်တွင် ไม่ (mâi) ကို ထည့်ရသည်။', '[{"thai": "เขาไม่ไป", "phonetic": "kăo mâi bpai", "english": "He does not go.", "myanmar": "သူ မသွားဘူး။"}]', 2),
('g-103', 'course-1', 1, 'Yes/No Questions with ไหม (măi)', 'ไหม (măi) ဖြင့် မေးခွန်းမေးခြင်း', 'Add ไหม (măi) at the end of a sentence to turn it into a yes/no question.', 'ဝါကျအဆုံးတွင် ไหม (măi) ထည့်ခြင်းဖြင့် ဟုတ်/မဟုတ် (Yes/No) မေးခွန်းဖြစ်စေသည်။', '[{"thai": "คุณหิวไหม", "phonetic": "kun hĭw măi", "english": "Are you hungry?", "myanmar": "ခင်ဗျား ဗိုက်ဆာလား။"}]', 3),
('g-104', 'course-1', 2, 'Past Tense Marker แล้ว (láew)', 'ပြီးခဲ့သောအချိန်ပြ แล้ว (láew)', 'แล้ว (láew) means "already" and is placed at the end of a sentence to indicate a past action.', 'แล้ว (láew) သည် "ပြီးပြီ" ဟု အဓိပ္ပါယ်ရပြီး ဝါကျအဆုံးတွင်ထား၍ အတိတ်ကာလကို ပြသည်။', '[{"thai": "ฉันกินแล้ว", "phonetic": "chăn gin láew", "english": "I already ate.", "myanmar": "ကျွန်တော် စားပြီးပြီ။"}]', 4),
('g-105', 'course-1', 2, 'Future Tense Marker จะ (jà)', 'အနာဂတ်ကာလပြ จะ (jà)', 'จะ (jà) means "will" and is placed before the verb to indicate future tense.', 'จะ (jà) သည် "လိမ့်မည်" ဟု အဓိပ္ပါယ်ရပြီး ကြိယာရှေ့တွင်ထား၍ အနာဂတ်ကာလကို ပြသည်။', '[{"thai": "ฉันจะไปพรุ่งนี้", "phonetic": "chăn jà bpai prûng-née", "english": "I will go tomorrow.", "myanmar": "ကျွန်တော် မနက်ဖြန် သွားမယ်။"}]', 5),
('g-106', 'course-1', 2, 'Present Continuous กำลัง (gam-lang)', 'လက်ရှိဖြစ်ဆဲကာလပြ กำลัง (gam-lang)', 'กำลัง (gam-lang) is placed before the verb to show an action is currently happening.', 'กำลัง (gam-lang) ကို ကြိယာရှေ့တွင်ထား၍ လက်ရှိလုပ်ဆောင်နေဆဲဖြစ်ကြောင်း ပြသည်။', '[{"thai": "เขากำลังกิน", "phonetic": "kăo gam-lang gin", "english": "He is eating.", "myanmar": "သူ စားနေတယ်။"}]', 6),
('g-107', 'course-1', 3, 'Polite Particles ครับ/ค่ะ (kráp/kâ)', 'ယဉ်ကျေးသော စကားအဆုံးသတ်များ', 'ครับ (kráp) is used by male speakers, and ค่ะ (kâ) by female speakers at the end of sentences for politeness.', 'ครับ (kráp) ကို ယောကျ်ားလေးများ၊ ค่ะ (kâ) ကို မိန်းကလေးများက ယဉ်ကျေးမှုအရ ဝါကျအဆုံးတွင် သုံးသည်။', '[{"thai": "ขอบคุณครับ", "phonetic": "kòp kun kráp", "english": "Thank you (male speaker).", "myanmar": "ကျေးဇူးတင်ပါတယ် (ယောကျ်ားလေး)။"}]', 7),
('g-108', 'course-1', 3, 'The Verb "To Be" (เป็น / คือ)', 'ဖြစ်သည် ကြိယာ (เป็น / คือ)', 'เป็น (bpen) is used for state/status, while คือ (keu) is used for definitions/equations.', 'เป็น ကို အခြေအနေနှင့် အဆင့်အတန်းပြရာတွင် သုံးပြီး၊ คือ ကို အဓိပ္ပါယ်ဖွင့်ဆိုရာတွင် သုံးသည်။', '[{"thai": "เขาเป็นหมอ", "phonetic": "kăo bpen mŏr", "english": "He is a doctor.", "myanmar": "သူက ဆရာဝန်ဖြစ်တယ်။"}]', 8),
('g-109', 'course-1', 3, 'The Verb "To Have" (มี - mee)', 'ရှိသည် ကြိယာ มี (mee)', 'มี (mee) means "to have" or "there is/there are".', 'มี သည် "ရှိသည်" ဟု အဓိပ္ပါယ်ရသည်။', '[{"thai": "ฉันมีหมา", "phonetic": "chăn mee măa", "english": "I have a dog.", "myanmar": "ကျွန်တော့်မှာ ခွေးတစ်ကောင်ရှိတယ်။"}]', 9),
('g-110', 'course-1', 4, 'Wanting something อยาก (yàak)', 'လိုချินခြင်းပြ อยาก (yàak)', 'อยาก (yàak) + verb means "want to do something". (เอา is used for objects).', 'อยาก ကို ကြိယာရှေ့မှာထားပါက "လုပ်ချင်တယ်" လို့ အဓိပ္ပါယ်ရပါတယ်။ (ပစ္စည်းလိုချင်လျှင် เอา ကိုသုံးပါ)', '[{"thai": "ฉันอยากไป", "phonetic": "chăn yàak bpai", "english": "I want to go.", "myanmar": "ကျွန်တော် သွားချင်တယ်။"}]', 10),
('g-111', 'course-1', 4, 'Must / Have to ต้อง (dtông)', 'လုပ်ရမည်ပြ ต้อง (dtông)', 'ต้อง (dtông) is placed before the verb to indicate necessity or obligation.', 'ต้อง ကို ကြိယာရှေ့တွင်ထား၍ မဖြစ်မနေ လုပ်ရမည်ဟု ပြသည်။', '[{"thai": "ฉันต้องไป", "phonetic": "chăn dtông bpai", "english": "I must go.", "myanmar": "ကျွန်တော် သွားရမယ်။"}]', 11),
('g-112', 'course-1', 4, 'Can / Ability ได้ (dâai)', 'နိုင်သည်ပြ ได้ (dâai)', 'ได้ (dâai) placed after the verb means "can" (possibility/permission).', 'ได้ ကို ကြိယာနောက်တွင်ထား၍ "နိုင်သည်" သို့မဟုတ် "ခွင့်ပြုသည်" ဟု အဓိပ္ပါယ်ရသည်။', '[{"thai": "ทำได้ไหม", "phonetic": "tam dâai măi", "english": "Can you do it?", "myanmar": "လုပ်လို့ရလား။"}]', 12),
('g-113', 'course-1', 5, 'Adjective Placement', 'နာမဝိသေသန နေရာထားရှိပုံ', 'In Thai, adjectives always come AFTER the noun they describe.', 'ထိုင်းဘာသာတွင် နာမဝိသေသန (အထူးပြုစကားလုံး) သည် အမြဲတမ်း နာမ် (အရာဝတ္ထု) နောက်တွင် လိုက်သည်။', '[{"thai": "หมาใหญ่", "phonetic": "măa yài", "english": "Big dog", "myanmar": "ခွေးကြီး"}]', 13),
('g-114', 'course-1', 5, 'Who ใคร (krai)', 'ဘယ်သူ ใคร (krai)', 'ใคร (krai) means "who".', 'ใคร သည် "ဘယ်သူ" ဟု အဓိပ္ပါယ်ရသည်။', '[{"thai": "เขาคือใคร", "phonetic": "kăo keu krai", "english": "Who is he?", "myanmar": "သူ ဘယ်သူလဲ။"}]', 14),
('g-115', 'course-1', 5, 'What อะไร (à-rai)', 'ဘာလဲ อะไร (à-rai)', 'อะไร (à-rai) means "what".', 'อะไร သည် "ဘာလဲ" ဟု အဓိပ္ပါယ်ရသည်။', '[{"thai": "นี่คืออะไร", "phonetic": "nêe keu à-rai", "english": "What is this?", "myanmar": "ဒါ ဘာလဲ။"}]', 15),
('g-116', 'course-1', 6, 'Where ที่ไหน (têe-năi)', 'ဘယ်မှာ ที่ไหน (têe-năi)', 'ที่ไหน (têe-năi) means "where".', 'ที่ไหน သည် "ဘယ်မှာ" ဟု အဓိပ္ပါယ်ရသည်။', '[{"thai": "ห้องน้ำอยู่ที่ไหน", "phonetic": "hông náam yòo têe-năi", "english": "Where is the toilet?", "myanmar": "အိမ်သာ ဘယ်မှာလဲ။"}]', 16),
('g-117', 'course-1', 6, 'When เมื่อไหร่ (mêua-rài)', 'ဘယ်အချိန် เมื่อไหร่ (mêua-rài)', 'เมื่อไหร่ (mêua-rài) means "when".', 'เมื่อไหร่ သည် "ဘယ်အချိန်" ဟု အဓိပ္ပါယ်ရသည်။', '[{"thai": "คุณจะมาเมื่อไหร่", "phonetic": "kun jà maa mêua-rài", "english": "When will you come?", "myanmar": "ခင်ဗျား ဘယ်အချိန် လာမလဲ။"}]', 17),
('g-018-dup', 'course-1', 6, 'Classifiers ลักษณนาม', 'အရေအတွက်ပြစကားလုံး', 'Thai uses specific classifiers when counting (Noun + Number + Classifier).', 'ပစ္စည်းများကို ရေတွက်ရာတွင် သီးသန့်အရေအတွက်ပြစကားလုံး (ပစ္စည်း + ဂဏန်း + အမျိုးအစား) ပုံစံဖြင့် သုံးသည်။', '[{"thai": "หมา 2 ตัว", "phonetic": "măa sŏng dtua", "english": "2 dogs", "myanmar": "ခွေး ၂ ကောင်"}]', 18),
('g-019-dup', 'course-1', 7, 'Conjunction และ (láe)', 'နှင့် / ပြီးတော့ และ (láe)', 'และ (láe) means "and", used to connect nouns or clauses.', 'และ သည် "နှင့်" သို့မဟုတ် "ပြီးတော့" ဟု အဓိပ္ပါယ်ရပြီး စကားလုံး သို့မဟုတ် ဝါကျများကို ဆက်ပေးသည်။', '[{"thai": "ฉันและเขา", "phonetic": "chăn láe kăo", "english": "Me and him", "myanmar": "ကျွန်တော်နှင့် သူ"}]', 19),
('g-020-dup', 'course-1', 7, 'Conjunction แต่ (dtàe)', 'ဒါပေမဲ့ แต่ (dtàe)', 'แต่ (dtàe) means "but".', 'แต่ သည် "ဒါပေမဲ့" ဟု အဓိပ္ပါယ်ရသည်။', '[{"thai": "แพงแต่ดี", "phonetic": "paeng dtàe dee", "english": "Expensive but good", "myanmar": "ဈေးကြီးပေမဲ့ ကောင်းတယ်"}]', 20);
