name = "sirithai"
pages_build_output_dir = "dist"
compatibility_date = "2026-08-16"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "sirithai-db"
database_id = "ceba9320-4b75-46b5-8077-d96c4c627176"
