-- Correct Myanmar phonetic spellings in the existing alphabet table.
-- This migration only updates existing records; it does not create or replace a table.

UPDATE alphabet
SET phonetic_mm = CASE COALESCE(char, character)
  WHEN 'ก' THEN 'ကော ကိုင်'
  WHEN 'ข' THEN 'ခေါ ခိုင်'
  WHEN 'ฃ' THEN 'ခေါ ခွတ်'
  WHEN 'ค' THEN 'ခေါ ခွိုင်'
  WHEN 'ฅ' THEN 'ခေါ ခွန်'
  WHEN 'ฆ' THEN 'ခေါ ရခန်း'
  WHEN 'ง' THEN 'ငေါ ငူး'
  WHEN 'จ' THEN 'ဂျော ဂျာန်း'
  WHEN 'ฉ' THEN 'ချော ချင်း'
  WHEN 'ช' THEN 'ချော ချာင်း'
  WHEN 'ซ' THEN 'ဆော ဆိုး'
  WHEN 'ฌ' THEN 'ချော ချာ'
  WHEN 'ญ' THEN 'ယော ယင်း'
  WHEN 'ฎ' THEN 'ဒေါ ချဒါ'
  WHEN 'ฏ' THEN 'တော ပတက်'
  WHEN 'ฐ' THEN 'ထော ထာန်း'
  WHEN 'ฑ' THEN 'ထော မွန်ထိုး'
  WHEN 'ฒ' THEN 'ထော ဖူးထောက်'
  WHEN 'ณ' THEN 'နော နိန်း'
  WHEN 'ด' THEN 'ဒေါ ဒက်'
  WHEN 'ต' THEN 'တော တောက်'
  WHEN 'ถ' THEN 'ထော ထုန်း'
  WHEN 'ท' THEN 'ထော ထဟာန်း'
  WHEN 'ธ' THEN 'ထော ထုန်း'
  WHEN 'น' THEN 'နော နူး'
  WHEN 'บ' THEN 'ဘော ဘိုင်မိုင်'
  WHEN 'ป' THEN 'ပေါ ပလာ'
  WHEN 'ผ' THEN 'ဖော ဖွန်း'
  WHEN 'ฝ' THEN 'ဖော ဖာ'
  WHEN 'พ' THEN 'ဖော ဖာန်း'
  WHEN 'ฟ' THEN 'ဖော ဖန်း'
  WHEN 'ภ' THEN 'ဖော ဆမ်ဖောက်'
  WHEN 'ม' THEN 'မော မာ'
  WHEN 'ย' THEN 'ယော ယက်'
  WHEN 'ร' THEN 'ရော ရူးအာ'
  WHEN 'ล' THEN 'လော လင်း'
  WHEN 'ว' THEN 'ဝေါ ဝဲန်း'
  WHEN 'ศ' THEN 'ဆော ဆာလာ'
  WHEN 'ษ' THEN 'ဆော ရူးစီ'
  WHEN 'ส' THEN 'ဆော ဆူးအာ'
  WHEN 'ห' THEN 'ဟော ဟိပ်'
  WHEN 'ฬ' THEN 'လော ကျူလာ'
  WHEN 'อ' THEN 'အော အာင်း'
  WHEN 'ฮ' THEN 'ဟော နို့က်ဟူး'
  ELSE phonetic_mm
END
WHERE lower(type) = 'consonant';

UPDATE alphabet
SET phonetic_mm = CASE COALESCE(char, character)
  WHEN '-ะ' THEN 'အ'
  WHEN '-า' THEN 'အာ'
  WHEN 'ิ' THEN 'အိ'
  WHEN 'ี' THEN 'အီ'
  WHEN 'ึ' THEN 'အွိ'
  WHEN 'ื' THEN 'အွီ'
  WHEN 'ุ' THEN 'အု'
  WHEN 'ู' THEN 'အူ'
  WHEN 'เ-ะ' THEN 'အေ့'
  WHEN 'เ-' THEN 'အေ'
  WHEN 'แ-ะ' THEN 'အဲ့'
  WHEN 'แ-' THEN 'အဲ'
  WHEN 'โ-ะ' THEN 'အို့'
  WHEN 'โ-' THEN 'အို'
  WHEN 'เ-าะ' THEN 'အော့'
  WHEN '-อ' THEN 'အော်'
  WHEN 'เ-อะ' THEN 'အာ့'
  WHEN 'เ-อ' THEN 'အာ'
  WHEN 'เ-ียะ' THEN 'အီယာ့'
  WHEN 'เ-ีย' THEN 'အီယာ'
  WHEN 'เ-ือะ' THEN 'အွအာ့'
  WHEN 'เ-ือ' THEN 'အွအာ'
  WHEN 'ัวะ' THEN 'အူဝါ့'
  WHEN 'ัว' THEN 'အူဝါ'
  WHEN 'ำ' THEN 'အမ်'
  WHEN 'ใ-' THEN 'အိုင်'
  WHEN 'ไ-' THEN 'အိုင်'
  WHEN 'เ-า' THEN 'အောက်'
  WHEN 'ฤ' THEN 'ရึ'
  WHEN 'ฤๅ' THEN 'ရူး'
  WHEN 'ฦ' THEN 'လึ'
  WHEN 'ฦๅ' THEN 'လူး'
  ELSE phonetic_mm
END
WHERE lower(type) = 'vowel';
